Las matrices especiales son aquellas que cumplen propiedades únicas que las hacen fundamentales en matemáticas, física, ingeniería y machine learning.

## Matriz Identidad In​


Es una matriz cuadrada con unos en la diagonal principal y ceros en el resto. Es el elemento neutro de la multiplicación matricial. Esto significa que multiplicar por la identidad no cambia el vector o matriz.

In [1]:
import numpy as np

I = np.eye(3)  # Matriz identidad 3x3
A = np.array([[2, 3, 4],
              [1, 0, 5],
              [7, 2, 1]])

print("Matriz identidad:\n", I)
print("A * I =\n", np.dot(A, I))


Matriz identidad:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
A * I =
 [[2. 3. 4.]
 [1. 0. 5.]
 [7. 2. 1.]]


## Matriz inversa

Es otra matriz que, al multiplicarse por 𝐴, da como resultado la identidad: 



A debe ser cuadrada y el determinante de 𝐴 debe ser distinto de cero

In [3]:
A = np.array([[4, 7],
              [2, 6]])

A_inv = np.linalg.inv(A)
print("Matriz inversa:\n", A_inv)

# Comprobación
print("A * A_inv =\n", np.dot(A, A_inv).round())


Matriz inversa:
 [[ 0.6 -0.7]
 [-0.2  0.4]]
A * A_inv =
 [[ 1. -0.]
 [ 0.  1.]]


Aunque matemáticamente se puede usar la inversa, numéricamente es mejor resolver sistemas con:

np.linalg.solve(A, b)

## Matriz singular

Es una matriz que no tiene inversa, su determinante es 0, Sus filas o columnas son linealmente dependientes (una es combinación lineal de otras).

In [6]:
singular = np.array([[1, 2],
                     [2, 4]])  # Fila 2 = 2 × Fila 1

print("Determinante:", np.linalg.det(singular))

try:
    np.linalg.inv(singular)
except np.linalg.LinAlgError:
    print("Error: la matriz es singular y no tiene inversa.")


Determinante: 0.0
Error: la matriz es singular y no tiene inversa.


Una matriz singular aplasta el espacio: transforma un área o volumen en una línea o punto. Esto significa que la transformación pierde información y no puede revertirse.

In [14]:
identidad = np.eye(5)


A = np.array([[2, 3, 1, 4, 5], [1, 2, 3, 4, 5], [2, 3, 4, 1, 5],[2, 3, 4, 1, 5],[2, 1, 3, 4, 5]])

producto = A * identidad
print(producto)

[[2. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 4. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 5.]]


In [15]:
print(np.dot(identidad, A))

[[2. 3. 1. 4. 5.]
 [1. 2. 3. 4. 5.]
 [2. 3. 4. 1. 5.]
 [2. 3. 4. 1. 5.]
 [2. 1. 3. 4. 5.]]


In [33]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [8, 9, 3]])

inversa = np.linalg.inv(matrix)
producto = np.dot(matrix, inversa)

print(producto.round())

[[ 1. -0.  0.]
 [ 0.  1.  0.]
 [ 0. -0.  1.]]


In [35]:
import numpy as np

m = np.array([[2, 1],
              [1, -3]])
b = np.array([5, -4])

solucion = np.linalg.solve(m, b)
print("Solución:", solucion)


Solución: [1.57142857 1.85714286]
