In [1]:
import numpy as np

Las matrices diagonales son un tipo especial de matrices que tienen un valor numérico en cada una de las posiciones de su diagonal principal, mientras que todos los demás elementos fuera de esta diagonal son cero. Estas matrices son de gran importancia en el álgebra lineal debido a su simplicidad y características únicas. Pueden no necesariamente ser cuadradas, es decir, tener el mismo número de filas y columnas, aunque las matrices diagonales cuadradas son las más comunes y estudiadas.

¿Cómo representamos una matriz diagonal en Python?
En Python, las matrices diagonales se pueden crear fácilmente utilizando librerías como numpy. A continuación, se muestra cómo crear una matriz diagonal:

In [2]:
vector = np.array([1, 2, 3, 4, 5])

matriz = np.diag(vector)

print(matriz)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


Una matriz diagonal siempre es cuadrada?

In [3]:
print(matriz[0:4, 0:3])

[[1 0 0]
 [0 2 0]
 [0 0 3]
 [0 0 0]]


In [4]:
print(matriz[0:3, 0:4])

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]]


In [9]:
A = np.diag([2,3,4,5])
v1 = np.array([[1,1,1,1]])
print(A)
print(v1)
print("-----------------------")
print(A.dot(v1.T))

[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]
[[1 1 1 1]]
-----------------------
[[2]
 [3]
 [4]
 [5]]


In [10]:
A_inv = np.diag([1/2, 1/3, 1/4, 1/5])
print(A_inv)

[[0.5        0.         0.         0.        ]
 [0.         0.33333333 0.         0.        ]
 [0.         0.         0.25       0.        ]
 [0.         0.         0.         0.2       ]]


In [11]:
identidad = A.dot(A_inv)

In [12]:
print(identidad)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [15]:
A_inv_calc = np.linalg.inv(A)
print(A_inv_calc)

[[0.5        0.         0.         0.        ]
 [0.         0.33333333 0.         0.        ]
 [0.         0.         0.25       0.        ]
 [0.         0.         0.         0.2       ]]


¿Qué caracteriza a las matrices simétricas?
Una matriz es simétrica si es igual a su transpuesta. Esto implica que los elementos situados en posiciones coincidentes con respecto a su diagonal principal son iguales. Para una matriz general, esto es más complicado que para las matrices diagonales, ya que estas últimas son siempre simétricas por definición: tienen ceros tanto abajo como arriba de la diagonal principal.

In [16]:
print(A.T)

[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]


In [17]:
print(A)

[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]
